name: Publish nuget package

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack it up
      run: dotnet pack -p:PackageVersion=1.0.${{ github.run_number }} --configuration Release
    - name: LS
      run: ls bin/Release/
    - name: add github nuget source to nuget cfg
      run: dotnet nuget add source --username koniin --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/koniin/index.json"
    - name: push package to github nuget source
      run: dotnet nuget push "bin/Release/super-nuget-package.1.0.${{ github.run_number }}.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
